CREATE OR REPLACE TASK TELCO.JOB.TK_SENT_STEP1_REFRESH_SYNTH
	warehouse=COMPUTE_WH
	schedule='USING CRON 0 9 * * MON-FRI Asia/Jakarta'
	COMMENT='Sentiment S1: refresh synthetic Play Store reviews'
	AS CALL TELCO.DS_SCRAPING.SP_REFRESH_PLAYSTORE_REVIEWS_SYNTETIC();
