CREATE OR REPLACE PROCEDURE TELCO.DATAMART.SP_REFRESH_REVIEW_MARTS_DWH_TELCO()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
  CREATE OR REPLACE TABLE DATAMART.TB_RPT_REVIEWS_YEARLY_NEG_DWH_TELCO AS SELECT 1;
  RETURN ''OK'';
END;
';