CREATE OR REPLACE PROCEDURE TELCO.DATAMART.SP_REFRESH_GENERAL_MARTS_DWH_TELCO()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
  truncate table datamart.TB_R_DATE;
  insert into datamart.TB_R_DATE select current_date();
  RETURN ''OK'';
END;
';